definitions:
  work_pool: &common_work_pool
    name: "local-docker"
    job_variables:
      image: "{{ image }}"

deployments:
- name: dep-sync-subflows
  version: null
  tags: [parent, sync]
  entrypoint: flows/sync_subflows.py:sync_subflows
  schedule: null
  work_pool: *common_work_pool

- name: dep-task-wrapped
  version: null
  tags: [parent, concurrent, async]
  entrypoint: flows/task_wrapped_deployments.py:task_wrapped_deployments
  schedule: null
  work_pool: *common_work_pool

- name: dep-child-a
  version: null
  tags: [child]
  entrypoint: flows/child_flows.py:child_flow_a
  schedule: null
  work_pool: *common_work_pool

- name: dep-child-b
  version: null
  tags: [child]
  entrypoint: flows/child_flows.py:child_flow_b
  schedule: null
  work_pool: *common_work_pool

- name: dep-child-c
  version: null
  tags: [child]
  entrypoint: flows/child_flows.py:child_flow_c
  schedule: null
  work_pool: *common_work_pool
  
- name: dep-child-d
  version: null
  tags: [child]
  entrypoint: flows/child_flows.py:child_flow_d
  schedule: null
  work_pool: *common_work_pool